version: "3.8"
services:
  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products
    ports:
      - "3307:3306"
    volumes:
      - "./.data/mysql:/var/lib/mysql"
